# Generated by Django 3.2.3 on 2021-05-29 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0002_auto_20210529_1638'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Serie',
        ),
    ]
